apiVersion: apps/v1
kind: Deployment
metadata:
  name: aigounad-app
  namespace: dev
spec:
  selector:
    matchLabels:
      app: aigounad
  template:
    metadata:
      labels:
        app: aigounad
    spec:
      containers:
      - name: aigounad
        image: wil42/playground:v2
        ports:
        - containerPort: 8888